trigger:
- main

pool:
  name: cafeteria-pool

variables:
  dockerHubServiceConnection: 'sc-dockerhub-cafeteria-v2'
  azureServiceConnection: 'sc-azure-cafeteria-v2'
  dockerHubRepo: 'fernandodelreal14/cafeteria-frontend'
  appName: 'cafeteria-frontend-app'
  dockerTag: '$(Build.BuildId)'

steps:

# 1. Checkout (OBLIGATORIO en self-hosted)
- checkout: self
  clean: true
  displayName: "Checkout del código"

# 2. Instalar Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: "Instalar Node.js"

# 3. Instalar dependencias (tu frontend no usa npm)
- script: echo "Frontend sin dependencias npm"
  workingDirectory: 'cafeteria-iteso-frontend'
  displayName: "Sin dependencias"

# 4. Login en Docker Hub v2
- task: Docker@2
  displayName: "Login en Docker Hub"
  inputs:
    command: login
    containerRegistry: $(dockerHubServiceConnection)

# 5. Construir imagen Docker del frontend
- task: Docker@2
  displayName: "Construir imagen Docker del frontend"
  inputs:
    command: build
    repository: $(dockerHubRepo)
    tags: |
      latest
      $(dockerTag)
    Dockerfile: 'cafeteria-iteso-frontend/Dockerfile'
    buildContext: 'cafeteria-iteso-frontend'

# 6. Push a Docker Hub
- task: Docker@2
  displayName: "Subir imagen del frontend a Docker Hub"
  inputs:
    command: push
    repository: $(dockerHubRepo)
    tags: |
      latest
      $(dockerTag)

# 7. Deploy en Azure Web App
- task: AzureWebAppContainer@1
  displayName: "Desplegar frontend a Azure Web App"
  inputs:
    azureSubscription: $(azureServiceConnection)
    appName: $(appName)
    imageName: "$(dockerHubRepo):latest"

