server {
    listen 80;
    server_name localhost;

    # Carpeta donde NGINX servirá tus archivos estáticos
    root /usr/share/nginx/html;

    # Página principal (home)
    index alumno.html;

    # Rutas estáticas
    location / {
        try_files $uri $uri/ /alumno.html;
    }

    # Manejo de archivos estáticos
    location ~* \.(css|js|png|jpg|jpeg|gif|ico)$ {
        try_files $uri =404;
    }
}

